=== joelbkoshy/sample/order.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    

    <xs:simpleType name="quan">
        <xs:restriction base="xs:decimal">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="100"/> 
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="article">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="head"/>
                <xs:element name="order" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                    <xs:sequence>
                        <xs:element name="code"/>
                        <xs:element name="id"/>
                        <xs:element name="name"/>
                        <xs:element name="quantity" type="quan"/>
                        <xs:element name="price"/>
                        <xs:element name="status"/>
                    </xs:sequence>
                </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== joelbkoshy/sample/order.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="order.xsl" type="text/xsl"?>

<article xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="order.xsd">
    <head>Order Details</head>

    <order>
        <code>PGS01</code>
        <id>PID10</id>
        <name>Keychain</name>
        <quantity>10</quantity>
        <price>200</price>
        <status>New</status>
    </order>

    <order>
        <code>PGS44</code>
        <id>PID03</id>
        <name>Rings</name>
        <quantity>2</quantity>
        <price>200</price>
        <status>Delivered</status>
    </order>
    <order>
        <code>PGS76</code>
        <id>PID07</id>
        <name>Plushies</name>
        <quantity>2</quantity>
        <price>2000</price>
        <status>Shipping</status>
    </order>
    <order>
        <code>PGS34</code>
        <id>PID11</id>
        <name>Moon Lmap</name>
        <quantity>1</quantity>
        <price>200</price>
        <status>Cancelled</status>
    </order>
    <order>
        <code>PGS12</code>
        <id>PID44</id>
        <name>Photo Frame</name>
        <quantity>1</quantity>
        <price>500</price>
        <status>Delivered</status>
    </order>

    

</article>
